version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "3001:8000"
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
